<?php
/**
* @file
* Install, update and uninstall functions for the OX install profile.
*/

/**
* Implements hook_install().
*
* Perform actions to set up the site for this profile.
*
* @see system_install()
*/
function site_module_test_install() {
  \Drupal::configFactory()->getEditable('system.theme')->set('default', 'claro')->save();
  \Drupal::configFactory()->getEditable('system.site')->set('name', 'Operations Dashboard')->save();
  \Drupal::configFactory()->getEditable('system.site')->set('page.front', '/sites/all')->save();
  \Drupal::service('module_installer')->install([
    'site_manager',
    'operations_ui',
    'devel',
    'devel_entity_updates',
    'key_auth',
    'rest',
  ]);
}
